TEXTS = {
    "step1_title": "",
    "step1_desc": "",
    "drop_zone": "Перетащить",
    "path_input_ph": "Ввести путь",
    "btn_pick": "Выбрать файл",
    "btn_load": "Загрузить и рассчитать",
    "file_dialog_title": "Выберите файл Excel",
    "file_not_found": "Файл не найден. Пожалуйста, укажите корректный путь.",
    "loading_status": "Загрузка (Может занять несколько или много) секунд)...",
    "loading_ms": "",
    "error_loading_title": "Ошибка загрузки",
    "error_title": "Ошибка",
    "search_lbl": "Поиск:",
    "search_ph": "Глобальный поиск...",
    "turnover_lbl": "Оборач. склада:",
    "col_subject": "Категория",
    "col_name": "Название",
    "col_article": "Артикул",
    "col_stock": "Остаток",
    "col_sales": "Заказы 30д",
    "col_avg": "Средн. в день",
    "col_wb_turnover": "Оборач. (WB)",
    "col_turnover": "Оборач. (План)",
    "col_target": "Цель (шт)",
    "col_need": "План (шт)",
    "col_ms_stock": "Остат. МС",
    "col_final": "К ОТГРУЗКЕ",
    "cb_rounding": "Округлять кратно 5",
    "cb_hide_zero": "Скрыть нулевые",
    "cb_exclude_minus": "Исключить нехватку МС",
    "cb_limit_ms": "Подгонять под остаток МС",
    "cb_turnover_filter": "Оборач. —",
    "turnover_filter_from": "от",
    "turnover_filter_to": "до",
    "ms_dialog_add_existing": "Добавить к существующей отгрузке",
    "ms_dialog_create_new": "Создать новую отгрузку",
    "ms_dialog_select_shipment": "Выберите отгрузку:",
    "ms_dialog_loading_shipments": "Загрузка списка отгрузок...",
    "msg_success_ms_add": "Товары добавлены к отгрузке!\\nНомер: {name}",
    "dup_dialog_title": "Найдены совпадения в отгрузке",
    "dup_dialog_desc": "Некоторые товары уже есть в отгрузке {name}. Выберите действие:",
    "dup_action_skip": "Пропустить",
    "dup_action_replace": "Заменить",
    "dup_action_add": "Добавить",
    "dup_col_article": "Артикул",
    "dup_col_existing": "В отгрузке",
    "dup_col_new": "Новое",
    "dup_col_result": "Итог",
    "dup_col_action": "Действие",
    "dup_summary_new": "Без конфликтов: {count} поз. ({qty} ед.)",
    "dup_summary_total": "Всего к добавлению: {count} поз. ({qty} ед.)",
    "cb_highlight_recent": "Поступления за",
    "recent_days_suffix": "дн.",
    "search_ph": "Поиск по артикулу или названию...",
    "btn_add_row": "Добавить строку",
    "btn_rem_row": "Удалить выбранную",
    "btn_undo": "Отменить",
    "btn_redo": "Вернуть",
    "add_row_title": "Добавление строки",
    "add_row_prompt1": "Введите артикул товара:",
    "add_row_prompt2": "Количество к отгрузке:",
    "item_manual": "Добавлено вручную",
    "wh_settings_title": "Управление складами",
    "wh_settings_hide": "Скрыть пустые склады (без остатков и продаж) автоматически",
    "step2_title": "Настройка складов",
    "btn_settings": "⚙️ Склады",
    "btn_next": "Итог >",
    "ms_dialog_ph_name": "Оставьте пустым для автогенерации",
    "ms_dialog_ph_desc": "Комментарий (необязательно)",
    "ms_dialog_lbl_name": "Номер документа:",
    "ms_dialog_lbl_desc": "Комментарий:",
    "step3_title": "Итоговая отгрузка по всем складам",
    "btn_back": "< Назад к настройкам",
    "btn_export_all": "Экспорт всех в один CSV",
    "search_step3": "Поиск по названию или артикулу...",
    "btn_excel": "Excel",
    "btn_ms": "В МС",
    "msg_empty_title": "Пусто",
    "msg_success_title": "Успех",
    "error_api_title": "Ошибка API",
    "error_loading": "Произошла ошибка:\n{e}",
    "ms_dialog_title": "Создание отгрузки МС: {warehouse_name}",
    "total_units": "Всего единиц к отгрузке: {grand_total}",
    "msg_empty_export": "Для склада {w} нет товаров к отгрузке.",
    "msg_success_export": "Файл отгрузки для {w} успешно сохранен!",
    "msg_empty_ms": "Для склада {w} нет товаров с найденной привязкой к Моему Складу.",
    "msg_success_ms": "Отгрузка успешно создана!\nНомер: {name}",
    "msg_error_ms": "Не удалось создать отгрузку:\n{ex}",
    "btn_recent_supplies": "Недавние поступления",
    "recent_dialog_title": "Недавние поступления",
    "recent_filter_label": "За последние",
    "recent_filter_suffix": "дн.",
    "recent_col_name": "Наименование",
    "recent_col_barcode": "ШК",
    "recent_col_article": "Артикул",
    "recent_col_stock": "На складе МС",
    "recent_col_qty": "К отгрузке",
    "recent_btn_add": "Добавить",
    "recent_info": "Показано: {count}",
    "btn_close": "Закрыть",
    "msg_no_supplies_title": "Нет данных",
    "msg_no_supplies_body": "Нет данных о поступлениях. Перезагрузите Excel-файл.",
    "msg_added_title": "Добавлено",
    "msg_added_body": "Товар {art} ({qty} шт.) добавлен в таблицу."
}
